# Generated by Django 2.2.6 on 2019-10-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Difficulty', models.CharField(max_length=6)),
                ('Marks', models.IntegerField()),
                ('Answer', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(default='tags')),
                ('Chapter', models.TextField(default='Chapter')),
                ('Section', models.TextField(default='Section')),
                ('Owner', models.TextField()),
                ('QbankNo', models.IntegerField()),
                ('IsModule', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('Qbank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qbank_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Marks', models.IntegerField(blank=True, null=True)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbank.Qbank_Main')),
            ],
        ),
    ]
