# Generated by Django 2.2.6 on 2019-11-14 22:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Priv', models.TextField()),
                ('Owner', models.TextField()),
                ('No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qbank_Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Difficulty', models.CharField(max_length=6)),
                ('Marks', models.IntegerField()),
                ('Answer', models.TextField(blank=True, default='', null=True)),
                ('tags', models.TextField(blank=True, default='', null=True)),
                ('Chapter', models.TextField(default='Chapter')),
                ('Section', models.TextField(default='Section')),
                ('Owner', models.TextField()),
                ('IsModule', models.BooleanField()),
                ('UploadNo', models.IntegerField(default=0)),
                ('QbankNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbank.Qbank')),
            ],
        ),
        migrations.CreateModel(
            name='Qpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Questions', models.TextField()),
                ('Marks', models.IntegerField(default=0)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.TextField()),
                ('Qbank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Qbank_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Marks', models.IntegerField(blank=True, null=True)),
                ('Parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbank.Qbank_Main')),
            ],
        ),
    ]
