# Generated by Django 2.2.6 on 2019-11-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbank_main',
            name='Answer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='qbank_main',
            name='tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
