# Generated by Django 2.2.6 on 2019-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0002_auto_20191107_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbank_main',
            name='UploadNo',
            field=models.IntegerField(default=0),
        ),
    ]
