# Generated by Django 2.2.7 on 2019-11-10 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0003_qbank_main_uploadno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Questions', models.TextField()),
                ('Marks', models.IntegerField(default=0)),
                ('Date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
