# Generated by Django 2.2.6 on 2019-11-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qbank', '0004_qpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qbank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Priv', models.TextField()),
                ('Owner', models.TextField()),
                ('No', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='qbank_main',
            name='QbankNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qbank.Qbank'),
        ),
    ]
